# Generated by Django 6.0.7 on 2026-07-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('DEACTIVATED', 'Deactivated'), ('GRADUATED', 'Graduated'), ('ALUMNI', 'Alumni')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('DEACTIVATED', 'Deactivated'), ('GRADUATED', 'Graduated'), ('ALUMNI', 'Alumni')], max_length=20)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
