# Generated by Django 6.0.7 on 2026-07-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PROMOTED', 'Promoted'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('DEACTIVATED', 'Deactivated'), ('READMITTED', 'Readmitted')], max_length=20),
        ),
    ]
