# Generated by Django 6.0.7 on 2026-07-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='school',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
