# Generated by Django 6.0.7 on 2026-07-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['-graduation_year']},
        ),
    ]
